### PR TITLE
Spm

### PR DESCRIPTION
**Pull request by bfernandesbfs**
# Support Swift Package Manager

Add support to SPM 

### Changed

* Add Package.swift
* Project folders organization for compatibility to structure Swift Package Manager
* Samples Apps grouped folders 
* Add Demo for SPM
* Fix Headers Objc
* Fix Build.sh

### CODE REVIEW

**Comment by bfernandesbfs** [comment]
Reference issue #91

**Comment by dogo** [comment]
+1 ! Awesome work!

**Comment by Vkt0r** [comment]
@reidmain Any chance we can have a review in this PR, please? Thanks

**Comment by alanzeino** [comment]
Hey @bfernandesbfs, thank you for the contribution! 

Unfortunately, this change is just way too large to take in its current form. It is unreviewable, at over 600 files changed.

Secondly, we want to make sure that changes like these are made after a discussion about the pros and cons of the approach, which didn't happen. You can imagine that as a project maintainer, to get a huge PR without an understanding of why it might be worth merging, can be a big investment of time to review. For example, I don't know which changes in this PR are 100% necessary and which are 'nice to have'.

So my suggestion is, let's come up with a plan of how we can make these PRs reviewable. We can split the changes into one commit per PR. Changes should be backwards compatible, i.e., none of them should break the master branch which we are working on adding spm support.

**Comment by bfernandesbfs** [comment]
thank you for feedback

I closed this PR and going reopen without folder change for better code review

**Pull request closed without merging**
