### PR TITLE
ability to use isAgnosticDevice under UITest

### PR DESCRIPTION
**Pull request by maxibello**
add new environment variable "IS_UI_TESTING" to user isAgnosticDevice flag under UI Tests.

### CODE REVIEW

**Comment by alanzeino** [comment]
We don't support taking snapshots inside ui test bundles. Not sure how this helps you, can you elaborate?

**Comment by alanzeino** [comment]
Can you reply to my question? Would like to understand this PR more.

**Comment by maxibello** [comment]
Hi! The reason of this PR - add possibility to test via simulators with device agnostic feature

**Comment by alanzeino** [comment]
> Hi! The reason of this PR - add possibility to test via simulators with device agnostic feature

This is already possible in the library. Can you explain further?

**Comment by maxibello** [comment]
In our application we always get nil for this expression (for UITests target):
`UIWindow *keyWindow = [[UIApplication sharedApplication] fb_strictKeyWindow];`
Maybe It is only our own problem

**Comment by alanzeino** [comment]
We removed `fb_strictKeyWindow` in version 4.0.0:

https://github.com/uber/ios-snapshot-test-case/blob/master/docs/LibraryVsApplicationTestBundles.md

You can use `agnosticOptions` to get a fine–grained file name for snapshot tests.

**Comment by maxibello** [comment]
@alanzeino btw screenSize option doesn't work for simulator:
`[[UIApplication sharedApplication] keyWindow]` returns nil
that's why I grabbed width and height from NSProcessInfo in my PR

**Pull request closed without merging**
