### PR TITLE
Add snapshot methods for Light and Dark mode screens

### PR DESCRIPTION
**Pull request by steve509**
Hello 👋, 

I work on a project that supports both Light and Dark mode and thought it would be nice to take snapshot references of views in different themes. This PR adds a few helper methods to accomplish that. Any feedback would be appreciated.

Cheers,
Steve

### CODE REVIEW

**Comment by k0nserv** [comment]
@steve509 Can you sign the CLA so this can be merged?

**Comment by steve509** [comment]
> @steve509 Can you sign the CLA so this can be merged?

👋@k0nserv, I've signed the CLA but I'm not sure why the check still says _Pending_. Let me know if you have any ideas on how I can re-run the check.

**Comment by steve509** [comment]
I'm going to re-open this to fix the CLA check.

**Comment by steve509** [comment]
Reopened here: https://github.com/uber/ios-snapshot-test-case/pull/125

If you don't mind taking a look again, thanks!

**Pull request closed without merging**
